import { IRepository } from '@/types'

export const PROJECTS: IRepository[] = [
  {
    id: 1,
    preview_img: '/media/projects/preview/otrium.png',
    img: '/media/projects/otrium.png',
    name: 'Otrium',
    description:
      'Otrium is an online fashion marketplace that sells unsold fashion items from top brands at discounted prices, promoting sustainability by reducing fashion waste.',
    html_url: 'https://otrium.com/',
    homepage: 'https://otrium.com/',
    last_commit_at: '08/2024',
    languages: [
      { name: 'TypeScript', size: 58 },
      { name: 'JavaScript', size: 12 },
      { name: 'Python', size: 10 },
      { name: 'MongoDB', size: 10 },
      { name: 'HTML', size: 5 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'Next.js',
      'Redux',
      'React-query',
      'Node.js',
      'TypeScript',
      'Django',
      'Tailwind CSS',
      'Webflow',
      'AWS',
      'Docker',
      'Cypress',
      'Storybook',
      'MongoDB',
      'Codefresh',
      'Bitbucket',
    ],
    role: 'Senior Fullstack Developer',
  },
  {
    id: 2,
    preview_img: '/media/projects/preview/mvphealthcare.png',
    img: '/media/projects/mvphealthcare.png',
    name: 'MVP Healthcare',
    description:
      'MVP Healthcare offers a telehealth system that enables users to easily connect with doctors and learn more about their symptoms.',
    html_url: 'https://mvphealthcare.com/',
    homepage: 'https://mvphealthcare.com/',
    last_commit_at: '01/2024',
    languages: [
      { name: 'TypeScript', size: 58 },
      { name: 'JavaScript', size: 12 },
      { name: 'Python', size: 10 },
      { name: 'PLSQL', size: 10 },
      { name: 'HTML', size: 5 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'Next.js',
      'Redux',
      'Node.js',
      'TypeScript',
      'Django',
      'Tailwind CSS',
      'AWS',
      'Docker',
      'Cypress',
      'Storybook',
      'SQL',
      'Github',
    ],
    role: 'Senior Fullstack Developer',
  },
  {
    id: 3,
    preview_img: '/media/projects/preview/hangara.png',
    img: '/media/projects/hangara.png',
    name: 'Hangara',
    description:
      'Hangara is a logistics platform focused on optimizing supply chain operations and providing efficient warehousing and transportation solutions for businesses.',
    html_url: 'https://hangara.com/',
    homepage: 'https://hangara.com/',
    last_commit_at: '09/2023',
    languages: [
      { name: 'TypeScript', size: 60 },
      { name: 'Go', size: 10 },
      { name: 'Python', size: 20 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML/CSS', size: 5 },
    ],
    topics: [
      'Angular',
      'React',
      'React-query',
      'Node.js',
      'Django',
      'Golang',
      'TypeScript',
      'Socket.io',
      'Tailwind CSS',
      'AWS',
      'MapBox',
      'Jest',
      'Cypress',
      'SQL',
      'Github',
    ],
    role: 'Senior FullStack Developer',
  },
  {
    id: 4,
    preview_img: '/media/projects/preview/blockchef.png',
    img: '/media/projects/blockchef.png',
    name: 'Blockchef',
    description:
      'Blockchef appears to be a platform focused on connecting customers with homemade food offerings, showcasing a variety of culinary creations available for purchase.',
    html_url: 'https://blockchef.com/',
    homepage: 'https://blockchef.com/',
    last_commit_at: '02/2023',
    languages: [
      { name: 'TypeScript', size: 70 },
      { name: 'JavaScript', size: 10 },
      { name: 'MongoDB', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Next', 'ECMAScript', 'TypeScript', 'React-query', 'Zustand', 'Socket.io', 'Vercel', 'Jest', 'MongoDB', 'Github'],
    role: 'Project Lead Developer',
  },
  {
    id: 5,
    preview_img: '/media/projects/preview/lunar.png',
    img: '/media/projects/lunar.png',
    name: 'LunarCrush',
    description:
      'LunarCrush focuses on trading and provides information and insights about cryptocurrencies, stocks, and NFTs (Non-Fungible Tokens).',
    html_url: 'https://lunarcrush.com/',
    homepage: 'https://lunarcrush.com/',
    last_commit_at: '09/2022',
    languages: [
      { name: 'JavaScript', size: 28 },
      { name: 'TypeScript', size: 50 },
      { name: 'PLSQL', size: 2 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Remix', 'ECMAScript', 'TypeScript', 'Tailwind', 'D3', 'AWS', 'Docker', 'Cypress', 'Storybook', 'SQL', 'Github'],
    role: 'Senior Fullstack Developer',
  },
  {
    id: 6,
    preview_img: '/media/projects/preview/cru.png',
    img: '/media/projects/cru.png',
    name: 'MPDX / Cru.org',
    description: 'An interdenominational Christian parachurch organization, 5k+ enterprise-sized company',
    html_url: 'https://next.mpdx.org/',
    homepage: 'https://next.mpdx.org/',
    last_commit_at: '01/2022',
    languages: [
      { name: 'JavaScript', size: 30 },
      { name: 'TypeScript', size: 40 },
      { name: 'Python', size: 15 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: [
      'React',
      'Next.js',
      'Zustand',
      'TypeScript',
      'Node.js',
      'Knex',
      'Django',
      'Material-UI',
      'Storybook',
      'Docker',
      'Okta',
      'Github',
    ],
    role: 'Senior Frontend Developer',
  },
  {
    id: 7,
    preview_img: '/media/projects/preview/odigeo.png',
    img: '/media/projects/odigeo.png',
    name: 'eDreams ODIGEO Connect',
    description:
      'This website belongs to eDreams ODIGEO Connect, a platform that allows hoteliers to list their properties and increase bookings.',
    html_url: 'https://odigeoconnect.com/',
    homepage: 'https://odigeoconnect.com/',
    last_commit_at: '06/2021',
    languages: [
      { name: 'JavaScript', size: 30 },
      { name: 'TypeScript', size: 50 },
      { name: 'HTML', size: 15 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Gatsby', 'TypeScript', 'Tailwind', 'AWS', 'Webpack', 'Jest', 'Cypress', 'Storybook', 'Github'],
    role: 'Lead UI Engineer',
  },
  {
    id: 8,
    preview_img: '/media/projects/preview/flux.jpg',
    img: '/media/projects/flux.jpg',
    name: 'Driveflux',
    description: 'The cars and motorcycles lending service in Malaysia',
    html_url: 'https://driveflux.com/',
    homepage: 'https://driveflux.com/',
    last_commit_at: '10/2020',
    languages: [
      { name: 'JavaScript', size: 50 },
      { name: 'TypeScript', size: 30 },
      { name: 'MongoDB', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Node.js', 'Express.js', 'MongoDB', 'AWS', 'Docker', 'Jest', 'Storybook', 'Github'],
    role: 'Senior Full Stack Developer',
  },
  {
    id: 9,
    preview_img: '/media/projects/preview/taskade.png',
    img: '/media/projects/taskade.png',
    name: 'Taskade',
    description: 'The unified collaboration hub for modern teams',
    html_url: 'https://taskade.com/',
    homepage: 'https://taskade.com/',
    last_commit_at: '02/2020',
    languages: [
      { name: 'JavaScript', size: 20 },
      { name: 'TypeScript', size: 60 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['Angular', 'Vue', 'Node.js', 'Koa', 'SQL', 'AWS', 'Docker', 'Jest', 'Storybook', 'Github'],
    role: 'Fullstack Developer',
  },
  {
    id: 10,
    preview_img: '/media/projects/preview/groupon.png',
    img: '/media/projects/groupon.png',
    name: 'Groupon',
    description:
      'LivingSocial, a marketplace under Groupon, is a prominent website that offers daily deals for a wide range of activities and items in various cities.',
    html_url: 'https://groupon.com/',
    homepage: 'https://groupon.com/',
    last_commit_at: '07/2019',
    languages: [
      { name: 'JavaScript', size: 60 },
      { name: 'Ruby', size: 20 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Next.js', 'Ruby', 'Selenium', 'Lodash', 'PLSQL', 'AWS', 'Docker', 'Storybook', 'Tailwind CSS', 'Github'],
    role: 'Senior Frontend Developer',
  },
  {
    id: 11,
    preview_img: '/media/projects/preview/iseatz.png',
    img: '/media/projects/iseatz.png',
    name: 'iSeatz',
    description:
      'The iSeatz is a comprehensive platform that offers ancillary management systems, travel rewards programs, custom solutions, and modules for travel and lifestyle products.',
    html_url: 'https://iseatz.com/',
    homepage: 'https://iseatz.com/',
    last_commit_at: '11/2018',
    languages: [
      { name: 'JavaScript', size: 30 },
      { name: 'TypeScript', size: 30 },
      { name: 'Ruby', size: 20 },
      { name: 'PLSQL', size: 5 },
      { name: 'HTML', size: 10 },
      { name: 'CSS', size: 5 },
    ],
    topics: ['React', 'Angular', 'three.js', 'Ruby on Rails', 'PLSQL', 'AWS', 'Docker', 'Bootstrap', 'Tailwind CSS', 'Github'],
    role: 'Frontend Developer',
  },
]
